apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-config
  namespace: gitlab
data:
  external_scheme: https
  external_hostname: gitlab.@GITLAB_GKE_DOMAIN@
  registry_external_scheme: https
  registry_external_hostname: registry.@GITLAB_GKE_DOMAIN@
  mattermost_external_scheme: https
  mattermost_external_hostname: mattermost.@GITLAB_GKE_DOMAIN@
  mattermost_app_uid: aadas
  postgres_user: gitlab
  postgres_db: gitlab_production
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secrets
  namespace: gitlab
data:
  postgres_password: NDl1ZjNtenMxcWR6NXZnbw==
  initial_shared_runners_registration_token: NDl1ZjNtenMxcWR6NXZnbw==
  mattermost_app_secret: NDl1ZjNtenMxcWR6NXZnbw==
