apiVersion: v1
kind: Service
metadata:
  name: git
  namespace: gitlab
  labels:
    app: git
spec:
  externalIPs: [192.168.1.147]
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: ssh
      port: 22
      targetPort: ssh
      protocol: TCP
  selector:
    app: git
