apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-configmap
  namespace: gitlab
data:
  ## This is used by GitLab Omnibus as the primary means of configuration.
  ## ref: https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template
  ##
  gitlab_omnibus_config: |
    external_url 'http://example.ii.org.nz'
    gitlab_rails['initial_root_password'] = "P@ssw0rd"
    gitlab_rails['gitlab_shell_ssh_port'] = 2222
